# Generated by Django 6.0.4 on 2026-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва валюти')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс продажу')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
                'ordering': ['-date'],
            },
        ),
    ]
